/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author guali
 */
public class FormularioDiccionario extends javax.swing.JFrame {

    /**
     * Creates new form FormularioDiccionario
     */
    public FormularioDiccionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Limpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AgregarPalabra = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        IdiomaTraducir = new javax.swing.JComboBox<>();
        palabraTraducir = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IdiomaTraductor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        traduccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Limpiar2 = new javax.swing.JButton();
        IdiomaTraducir2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        PalabraTraducir2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IdiomaTraductor2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        PalabraTraducida = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        traducir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("TRADUCTOR");

        AgregarPalabra.setText("Agregar palabra");
        AgregarPalabra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarPalabraActionPerformed(evt);
            }
        });

        jLabel2.setText("Idioma a traducir");

        IdiomaTraducir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar idioma", "Español", "Ingles", "Frances", "Italiano" }));
        IdiomaTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaTraducirActionPerformed(evt);
            }
        });

        palabraTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palabraTraducirActionPerformed(evt);
            }
        });

        jLabel3.setText("Palabra a Traduccir");

        IdiomaTraductor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar idioma", "Español", "Ingles", "Frances", "Italiano" }));
        IdiomaTraductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaTraductorActionPerformed(evt);
            }
        });

        jLabel4.setText("Idioma Traductor");

        traduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traduccionActionPerformed(evt);
            }
        });

        jLabel5.setText("Traduccion");

        Limpiar2.setText("Limpiar");
        Limpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar2ActionPerformed(evt);
            }
        });

        IdiomaTraducir2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Idioma", "Español", "Ingles", "Italiano", "Frances" }));
        IdiomaTraducir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaTraducir2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Idioma a traducir");

        PalabraTraducir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalabraTraducir2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Palabra a Traducir");

        IdiomaTraductor2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Idioma", "Español", "Ingles", "Italiano", "Frances" }));
        IdiomaTraductor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdiomaTraductor2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Idioma Traductor");

        PalabraTraducida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalabraTraducidaActionPerformed(evt);
            }
        });

        jLabel9.setText("Palabra traducida");

        traducir.setText("Traducir");
        traducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traducirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(traduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(IdiomaTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(palabraTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(IdiomaTraductor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(103, 103, 103)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(63, 63, 63))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(IdiomaTraducir2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PalabraTraducir2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(IdiomaTraductor2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(Limpiar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AgregarPalabra)
                        .addGap(19, 19, 19)))
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel7)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(PalabraTraducida, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(Limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(traducir)
                .addGap(126, 126, 126))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdiomaTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palabraTraducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdiomaTraductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(traduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Limpiar)
                            .addComponent(traducir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PalabraTraducir2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdiomaTraductor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdiomaTraducir2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PalabraTraducida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarPalabra)
                    .addComponent(Limpiar2))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private java.util.HashMap<String, String> diccionarioEsIng = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioIngEs = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioEsIta = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioItaEs = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioEsFra = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioFraEs = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioIngIta = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioItaIng = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioIngFra = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioFraIng = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioFraIta = new java.util.HashMap<>();
private java.util.HashMap<String, String> diccionarioItaFra = new java.util.HashMap<>();

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        // TODO add your handling code here:
        traduccion.setText("");
        palabraTraducir.setText("");

    }//GEN-LAST:event_LimpiarActionPerformed

    private void PalabraTraducidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalabraTraducidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PalabraTraducidaActionPerformed

    private void traduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traduccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_traduccionActionPerformed

    private void Limpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar2ActionPerformed
        // TODO add your handling code here:
        PalabraTraducida.setText("");
        PalabraTraducir2.setText("");
    }//GEN-LAST:event_Limpiar2ActionPerformed

    private void IdiomaTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaTraducirActionPerformed
      

    }//GEN-LAST:event_IdiomaTraducirActionPerformed

    private void IdiomaTraductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaTraductorActionPerformed
        
    }//GEN-LAST:event_IdiomaTraductorActionPerformed

    private void palabraTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palabraTraducirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_palabraTraducirActionPerformed

    private void IdiomaTraducir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaTraducir2ActionPerformed
       

    }//GEN-LAST:event_IdiomaTraducir2ActionPerformed

    private void IdiomaTraductor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdiomaTraductor2ActionPerformed
        

    }//GEN-LAST:event_IdiomaTraductor2ActionPerformed

    private void AgregarPalabraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarPalabraActionPerformed
        // TODO add your handling code here:
        String idiomaOrigen = (String) IdiomaTraducir2.getSelectedItem();
    String idiomaDestino = (String) IdiomaTraductor2.getSelectedItem();
    String palabraOrigen = PalabraTraducir2.getText().trim().toLowerCase();
    String palabraDestino = PalabraTraducida.getText().trim().toLowerCase();

    // Validaciones básicas
    if (idiomaOrigen.equals("Seleccionar idioma") || idiomaDestino.equals("Seleccionar idioma")) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona ambos idiomas.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (idiomaOrigen.equals(idiomaDestino)) {
        JOptionPane.showMessageDialog(this, "El idioma de origen y destino deben ser diferentes.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (palabraOrigen.isEmpty() || palabraDestino.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor ingresa palabras en ambos campos.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Agregar la palabra al diccionario correspondiente
    switch (idiomaOrigen + "-" + idiomaDestino) {
        case "Español-Ingles":
            diccionarioEsIng.put(palabraOrigen, palabraDestino);
            diccionarioIngEs.put(palabraDestino, palabraOrigen);
            break;
        case "Español-Italiano":
            diccionarioEsIta.put(palabraOrigen, palabraDestino);
            diccionarioItaEs.put(palabraDestino, palabraOrigen);
            break;
        case "Español-Frances":
            diccionarioEsFra.put(palabraOrigen, palabraDestino);
            diccionarioFraEs.put(palabraDestino, palabraOrigen);
            break;
        case "Ingles-Español":
            diccionarioIngEs.put(palabraOrigen, palabraDestino);
            diccionarioEsIng.put(palabraDestino, palabraOrigen);
            break;
        case "Ingles-Italiano":
            diccionarioIngIta.put(palabraOrigen, palabraDestino);
            diccionarioItaIng.put(palabraDestino, palabraOrigen);
            break;
        case "Ingles-Frances":
            diccionarioIngFra.put(palabraOrigen, palabraDestino);
            diccionarioFraIng.put(palabraDestino, palabraOrigen);
            break;
        case "Italiano-Español":
            diccionarioItaEs.put(palabraOrigen, palabraDestino);
            diccionarioEsIta.put(palabraDestino, palabraOrigen);
            break;
        case "Italiano-Ingles":
            diccionarioItaIng.put(palabraOrigen, palabraDestino);
            diccionarioIngIta.put(palabraDestino, palabraOrigen);
            break;
        case "Italiano-Frances":
            diccionarioItaFra.put(palabraOrigen, palabraDestino);
            diccionarioFraIta.put(palabraDestino, palabraOrigen);
            break;
        case "Frances-Español":
            diccionarioFraEs.put(palabraOrigen, palabraDestino);
            diccionarioEsFra.put(palabraDestino, palabraOrigen);
            break;
        case "Frances-Ingles":
            diccionarioFraIng.put(palabraOrigen, palabraDestino);
            diccionarioIngFra.put(palabraDestino, palabraOrigen);
            break;
        case "Frances-Italiano":
            diccionarioFraIta.put(palabraOrigen, palabraDestino);
            diccionarioItaFra.put(palabraDestino, palabraOrigen);
            break;
        default:
            JOptionPane.showMessageDialog(this, "Combinación de idiomas no soportada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
    }

    // Mensaje de confirmación
    JOptionPane.showMessageDialog(this, "Palabra agregada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);

    // Limpiar los campos
    PalabraTraducir2.setText("");
    PalabraTraducida.setText("");
    }//GEN-LAST:event_AgregarPalabraActionPerformed

    private void traducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traducirActionPerformed
       
        String palabraIngresada = palabraTraducir.getText().trim().toLowerCase();
    String idiomaOrigen = (String) IdiomaTraducir.getSelectedItem();
    String idiomaDestino = (String) IdiomaTraductor.getSelectedItem();

    // Validaciones iniciales
    if (idiomaOrigen.equals("Seleccionar idioma") || idiomaDestino.equals("Seleccionar idioma")) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona ambos idiomas.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (idiomaOrigen.equals(idiomaDestino)) {
        JOptionPane.showMessageDialog(this, "El idioma de origen y destino deben ser diferentes.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Diccionario usado para traducir
    String traduccion = null;

    switch (idiomaOrigen + "-" + idiomaDestino) {
        case "Español-Ingles":
            traduccion = diccionarioEsIng.get(palabraIngresada);
            break;
        case "Español-Italiano":
            traduccion = diccionarioEsIta.get(palabraIngresada);
            break;
        case "Español-Frances":
            traduccion = diccionarioEsFra.get(palabraIngresada);
            break;
        case "Ingles-Español":
            traduccion = diccionarioIngEs.get(palabraIngresada);
            break;
        case "Ingles-Italiano":
            traduccion = diccionarioIngIta.get(palabraIngresada);
            break;
        case "Ingles-Frances":
            traduccion = diccionarioIngFra.get(palabraIngresada);
            break;
        case "Italiano-Español":
            traduccion = diccionarioItaEs.get(palabraIngresada);
            break;
        case "Italiano-Ingles":
            traduccion = diccionarioItaIng.get(palabraIngresada);
            break;
        case "Italiano-Frances":
            traduccion = diccionarioItaFra.get(palabraIngresada);
            break;
        case "Frances-Español":
            traduccion = diccionarioFraEs.get(palabraIngresada);
            break;
        case "Frances-Ingles":
            traduccion = diccionarioFraIng.get(palabraIngresada);
            break;
        case "Frances-Italiano":
            traduccion = diccionarioFraIta.get(palabraIngresada);
            break;
        default:
            JOptionPane.showMessageDialog(this, "Combinación de idiomas no soportada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
    }

    // Verifica si la traducción existe
    if (traduccion == null) {
        JOptionPane.showMessageDialog(this, "Palabra no existente en el diccionario.", "Error", JOptionPane.ERROR_MESSAGE);
        PalabraTraducida.setText("");
    } else {
        // Muestra la traducción
        PalabraTraducida.setText(traduccion);
    }
    }//GEN-LAST:event_traducirActionPerformed

    private void PalabraTraducir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalabraTraducir2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PalabraTraducir2ActionPerformed
  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioDiccionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioDiccionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioDiccionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioDiccionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioDiccionario().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AgregarPalabra;
    private javax.swing.JComboBox<String> IdiomaTraducir;
    private javax.swing.JComboBox<String> IdiomaTraducir2;
    private javax.swing.JComboBox<String> IdiomaTraductor;
    private javax.swing.JComboBox<String> IdiomaTraductor2;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Limpiar2;
    private javax.swing.JTextField PalabraTraducida;
    private javax.swing.JTextField PalabraTraducir2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField palabraTraducir;
    private javax.swing.JTextField traduccion;
    private javax.swing.JButton traducir;
    // End of variables declaration//GEN-END:variables

}
